#include "MetalCInternal.hpp"

extern "C" {
MTL4BufferRange MTL4BufferRangeMake(const MTLBuffer* b, size_t offset, size_t length) { return MTL4BufferRange{b ? native<MTL::Buffer>(b)->gpuAddress() + offset : 0, length}; }
void MTL4ComputeCommandEncoderSetComputePipelineState(MTL4ComputeCommandEncoder* e, const MTLComputePipelineState* p) { if (e && p) native<MTL4::ComputeCommandEncoder>(e)->setComputePipelineState(native<MTL::ComputePipelineState>(p)); }
void MTL4ComputeCommandEncoderSetArgumentTable(MTL4ComputeCommandEncoder* e, const MTL4ArgumentTable* t) { if (e && t) native<MTL4::ComputeCommandEncoder>(e)->setArgumentTable(native<MTL4::ArgumentTable>(t)); }
void MTL4ComputeCommandEncoderBarrierAfterEncoderStages(MTL4ComputeCommandEncoder* e, MTLStages after, MTLStages before, MTL4VisibilityOptions v) { if (e) native<MTL4::ComputeCommandEncoder>(e)->barrierAfterEncoderStages(static_cast<MTL::Stages>(after), static_cast<MTL::Stages>(before), static_cast<MTL4::VisibilityOptions>(v)); }
void MTL4ComputeCommandEncoderEndEncoding(MTL4ComputeCommandEncoder* e) { if (e) native<MTL4::ComputeCommandEncoder>(e)->endEncoding(); }
void MTL4ComputeCommandEncoderDispatchThreads(MTL4ComputeCommandEncoder* e, MTLSize grid, MTLSize group) { if (e) native<MTL4::ComputeCommandEncoder>(e)->dispatchThreads(nativeSize(grid), nativeSize(group)); }
void MTL4ComputeCommandEncoderDispatchThreadgroups(MTL4ComputeCommandEncoder* e, MTLSize grid, MTLSize group) { if (e) native<MTL4::ComputeCommandEncoder>(e)->dispatchThreadgroups(nativeSize(grid), nativeSize(group)); }
void MTL4ComputeCommandEncoderCopyBuffer(MTL4ComputeCommandEncoder* e, const MTLBuffer* s, size_t so, const MTLBuffer* d, size_t destinationOffset, size_t size) { if (e && s && d) native<MTL4::ComputeCommandEncoder>(e)->copyFromBuffer(native<MTL::Buffer>(s), so, native<MTL::Buffer>(d), destinationOffset, size); }
void MTL4ComputeCommandEncoderCopyBufferToTexture(MTL4ComputeCommandEncoder* e, const MTLBuffer* s, size_t offset, size_t row, size_t image, MTLSize size, const MTLTexture* d, size_t slice, size_t level, MTLOrigin origin) { if (e && s && d) native<MTL4::ComputeCommandEncoder>(e)->copyFromBuffer(native<MTL::Buffer>(s), offset, row, image, nativeSize(size), native<MTL::Texture>(d), slice, level, nativeOrigin(origin)); }
void MTL4ComputeCommandEncoderBuildAccelerationStructure(MTL4ComputeCommandEncoder* e, const MTLAccelerationStructure* a, const MTL4AccelerationStructureDescriptor* d, MTL4BufferRange scratch) { if (e && a && d) native<MTL4::ComputeCommandEncoder>(e)->buildAccelerationStructure(native<MTL::AccelerationStructure>(a), native<MTL4::AccelerationStructureDescriptor>(d), nativeRange(scratch)); }
void MTL4ComputeCommandEncoderRefitAccelerationStructure(MTL4ComputeCommandEncoder* e, const MTLAccelerationStructure* s, const MTL4AccelerationStructureDescriptor* d, const MTLAccelerationStructure* destination, MTL4BufferRange scratch) { if (e && s && d && destination) native<MTL4::ComputeCommandEncoder>(e)->refitAccelerationStructure(native<MTL::AccelerationStructure>(s), native<MTL4::AccelerationStructureDescriptor>(d), native<MTL::AccelerationStructure>(destination), nativeRange(scratch)); }
}
