#pragma once
#include <Metal/MTLDefines.h>
#include <Metal/MTLTypes.h>
#include <Metal/MTLPixelFormat.h>
#include <Metal/MTLResource.h>
#include <Metal/MTLBuffer.h>
#include <Metal/MTLTexture.h>
#include <Metal/MTLAccelerationStructureTypes.h>
#include <Metal/MTLAccelerationStructure.h>
#include <Metal/MTLComputePipeline.h>
#include <Metal/MTLLibrary.h>
#include <Metal/MTLDrawable.h>
#include <Metal/MTLEvent.h>
#include <Metal/MTLResidencySet.h>
#include <Metal/MTLDevice.h>
#include <Metal/MTL4ArgumentTable.h>
#include <Metal/MTL4CommandAllocator.h>
#include <Metal/MTL4CommandBuffer.h>
#include <Metal/MTL4CommandEncoder.h>
#include <Metal/MTL4CommandQueue.h>
#include <Metal/MTL4LibraryDescriptor.h>
#include <Metal/MTL4LibraryFunctionDescriptor.h>
#include <Metal/MTL4ComputePipeline.h>
#include <Metal/MTL4Compiler.h>
#include <Metal/MTL4ComputeCommandEncoder.h>
#include <Metal/MTL4AccelerationStructure.h>
