#pragma once
#include <Metal/MTL4ComputeCommandEncoder.h>
#include <Metal/MTLAccelerationStructureTypes.h>
#include <Metal/MTLDefines.h>
#ifdef __cplusplus
extern "C" {
#endif
typedef struct MTL4AccelerationStructureDescriptor MTL4AccelerationStructureDescriptor;
typedef struct MTL4AccelerationStructureTriangleGeometryDescriptor MTL4AccelerationStructureTriangleGeometryDescriptor;
typedef struct MTL4PrimitiveAccelerationStructureDescriptor MTL4PrimitiveAccelerationStructureDescriptor;
typedef struct MTL4InstanceAccelerationStructureDescriptor MTL4InstanceAccelerationStructureDescriptor;

METAL_C_EXPORT MTL4AccelerationStructureTriangleGeometryDescriptor* MTL4AccelerationStructureTriangleGeometryDescriptorCreate(void);
METAL_C_EXPORT void MTL4AccelerationStructureTriangleGeometryDescriptorSetVertexBuffer(MTL4AccelerationStructureTriangleGeometryDescriptor* descriptor, MTL4BufferRange buffer);
METAL_C_EXPORT void MTL4AccelerationStructureTriangleGeometryDescriptorSetVertexFormat(MTL4AccelerationStructureTriangleGeometryDescriptor* descriptor, MTLAttributeFormat format);
METAL_C_EXPORT void MTL4AccelerationStructureTriangleGeometryDescriptorSetVertexStride(MTL4AccelerationStructureTriangleGeometryDescriptor* descriptor, size_t stride);
METAL_C_EXPORT void MTL4AccelerationStructureTriangleGeometryDescriptorSetIndexBuffer(MTL4AccelerationStructureTriangleGeometryDescriptor* descriptor, MTL4BufferRange buffer);
METAL_C_EXPORT void MTL4AccelerationStructureTriangleGeometryDescriptorSetIndexType(MTL4AccelerationStructureTriangleGeometryDescriptor* descriptor, MTLIndexType type);
METAL_C_EXPORT void MTL4AccelerationStructureTriangleGeometryDescriptorSetTriangleCount(MTL4AccelerationStructureTriangleGeometryDescriptor* descriptor, size_t count);
METAL_C_EXPORT void MTL4AccelerationStructureTriangleGeometryDescriptorSetOpaque(MTL4AccelerationStructureTriangleGeometryDescriptor* descriptor, bool opaque);

METAL_C_EXPORT MTL4PrimitiveAccelerationStructureDescriptor* MTL4PrimitiveAccelerationStructureDescriptorCreate(void);
METAL_C_EXPORT void MTL4PrimitiveAccelerationStructureDescriptorSetGeometryDescriptors(MTL4PrimitiveAccelerationStructureDescriptor* descriptor, MTL4AccelerationStructureTriangleGeometryDescriptor* const* geometryDescriptors, size_t count);
METAL_C_EXPORT void MTL4PrimitiveAccelerationStructureDescriptorSetUsage(MTL4PrimitiveAccelerationStructureDescriptor* descriptor, MTLAccelerationStructureUsage usage);

METAL_C_EXPORT MTL4InstanceAccelerationStructureDescriptor* MTL4InstanceAccelerationStructureDescriptorCreate(void);
METAL_C_EXPORT void MTL4InstanceAccelerationStructureDescriptorSetInstanceDescriptorBuffer(MTL4InstanceAccelerationStructureDescriptor* descriptor, MTL4BufferRange buffer);
METAL_C_EXPORT void MTL4InstanceAccelerationStructureDescriptorSetInstanceDescriptorStride(MTL4InstanceAccelerationStructureDescriptor* descriptor, size_t stride);
METAL_C_EXPORT void MTL4InstanceAccelerationStructureDescriptorSetInstanceDescriptorType(MTL4InstanceAccelerationStructureDescriptor* descriptor, MTLAccelerationStructureInstanceDescriptorType type);
METAL_C_EXPORT void MTL4InstanceAccelerationStructureDescriptorSetInstanceCount(MTL4InstanceAccelerationStructureDescriptor* descriptor, size_t count);
METAL_C_EXPORT void MTL4InstanceAccelerationStructureDescriptorSetUsage(MTL4InstanceAccelerationStructureDescriptor* descriptor, MTLAccelerationStructureUsage usage);
#ifdef __cplusplus
}
#endif
